name: 'Format Code'

on:
  push:
    branches:
      - revision

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Format code
        run: npx prettier -w **/*.astro --cache
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[ci] format'
          branch: ${{ github.head_ref }}
